puts avx2 behind `#[cfg(..)]` instead of `is_x86_feature_detected!` to prevent crashes
on my aging laptop i7 encountered this trying to run the tests:

```
running 6 tests
error: process didn't exit successfully: `~/src/stream-
vbyte64/target/debug/deps/stream_vbyte64-737bc6dcae9b851f` (signal: 4,
SIGILL: illegal instruction)
```

This is a quick fix - did not take the time to identify the exact
culprit.